[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
path = "/aiResponse"
function = "aiResponse"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
